### PR TITLE
Start Work on auto Update

### PR DESCRIPTION
**Pull request by Iam2smart**
Started Working on the Ability to auto update from DSIMenuPlusPlus-Launcher

### CODE REVIEW

**Comment by Iam2smart** [comment]
I have not tested this yet and I have not added It to the GUI

**Comment by Zmxhawrhbg** [comment]
Tried to build it. As of right now, it fails to compile. `log.cpp` seems to error due to an open comment, which can be fixed. The other issue is that `date.cpp` references `main.h`, a file that doesn't exist. Changing it to `main.cpp` seems to error too, due to multiple definitions. It's probably fixable though.

**Comment by Iam2smart** [comment]
Yeah it does seem require a lot of work so I have been working on it from here and there

**Comment by Iam2smart** [comment]
Could you provide a log of the compiling

**Comment by Zmxhawrhbg** [comment]
[buildlog.txt](https://github.com/Robz8/DSiMenuPlusPlus-Launcher/files/2308716/buildlog.txt)
log.cpp is the main failure right now.

**Comment by Iam2smart** [comment]
Could you try now I delete the log creation because so much errors just have to adapt and if it fails send me a log. Thanks

**Comment by Zmxhawrhbg** [comment]
[buildlog.txt](https://github.com/Robz8/DSiMenuPlusPlus-Launcher/files/2312230/buildlog.txt)
This one seems to fail due to multiple definition errors in `main.cpp`.

**Pull request closed without merging**
